### ISSUE TITLE
Update python dependencies

### ISSUE THREAD

**Issue by afuetterer** [pangaea-data-publisher/fuji#380]
Some [dependency versions](https://github.com/pangaea-data-publisher/fuji/blob/master/pyproject.toml) are quite dated. Let's update those.

## Versions
```console
$ python -m pip list --outdated
Package                  Version Latest Type
------------------------ ------- ------ -----
beautifulsoup4           4.8.2   4.12.2 wheel
chardet                  3.0.4   5.2.0  wheel
click                    7.1.2   8.1.7  wheel
configparser             5.0.2   6.0.0  wheel
connexion                2.9.0   2.14.2 wheel
extruct                  0.13.0  0.16.0 wheel
Flask                    1.1.4   2.3.3  wheel
Flask-Cors               3.0.10  4.0.0  wheel
Flask-Limiter            2.0.0   3.5.0  wheel
idna                     2.10    3.4    wheel
IDUtils                  1.1.14  1.2.1  wheel
itsdangerous             1.1.0   2.1.2  wheel
Jinja2                   2.11.3  3.1.2  wheel 
jmespath                 0.10.0  1.0.1  wheel
jsonschema               3.2.0   4.19.0 wheel
levenshtein              0.12.0  0.21.1 wheel
MarkupSafe               2.0.1   2.1.3  wheel
openapi-schema-validator 0.1.6   0.6.0  wheel
openapi-spec-validator   0.3.3   0.6.0  wheel
pandas                   1.5.3   2.1.0  wheel
pyrsistent               0.16.1  0.19.3 wheel
PyYAML                   5.3.1   6.0.1  wheel
rapidfuzz                3.1.2   3.2.0  wheel
rdflib                   6.1.1   7.0.0  wheel
requests                 2.24.0  2.31.0 wheel
SPARQLWrapper            1.8.5   2.0.0  wheel
tika                     1.25    2.6.0  sdist
tldextract               3.1.2   3.4.4  wheel
urlextract               1.2.0   1.8.0  wheel
urllib3                  1.25.11 2.0.4  wheel
Werkzeug                 1.0.1   2.3.7  wheel
```

## Tasks

- [x] autosemver #376 
- [x] beautifulsoup4 #407
- [x] lxml #407
- [x] jmespath #407
- [x] configparser #407
- [x] idutils #407
- [x] requests #407
- [x] waitress #407
- [x] remove werkzeug (transitive dependency (connexion, flask)) #407
- [x] remove markupsafe (transitive dependency (connexion, jinja2)) #407
- [x] flask-cors #407
- [x] levenshtein #407
- [x] rapidfuzz #407
- [x] pyld #407
- [x] feedparser #407
- [x] connexion[swagger-ui]
- [x] pandas -> update requires Python >=3.9 #410
- [x] extruct: https://github.com/scrapinghub/extruct/blob/master/HISTORY.rst #410
- [x] flask-limiter: https://github.com/alisaifee/flask-limiter/blob/master/HISTORY.rst #410
- [x] pyyaml #410
- [x] tldextract: https://github.com/john-kurkowski/tldextract/blob/master/CHANGELOG.md #410
- [x] urlextract: https://github.com/lipoja/URLExtract/blob/master/CHANGELOG.rst #410
- [x] tika: https://github.com/chrismattmann/tika-python/compare/1.25...2.6.0 #410
- [x] sparqlwrapper: https://github.com/RDFLib/sparqlwrapper/blob/master/ChangeLog.txt #410
- [x] rdflib: https://github.com/RDFLib/rdflib/blob/main/CHANGELOG.md #410
- [x] flask updated to 2.2.5, 2.3 is not compatible with connexion #410

## Relevant
- pyRdfa3 -> project has been archived by the owner on Jun 21, 2022

Related: #357 #409

**Comment by afuetterer** [comment]
```
Checking dependencies
Package       Version Latest Type
------------- ------- ------ -----
extruct       0.13.0  0.16.0 wheel
Flask         2.2.5   2.3.3  wheel
Flask-Limiter 2.0.0   3.5.0  wheel
pandas        1.5.3   2.1.1  wheel
rdflib        6.3.2   7.0.0  wheel
setuptools    68.2.0  68.2.2 wheel
SPARQLWrapper 1.8.5   2.0.0  wheel
tika          1.25    2.6.0  sdist
Werkzeug      2.2.3   2.3.7  wheel
```

**Comment by afuetterer** [comment]
Is there a reason for the version constraint `flask-limiter<=2.0.0` @huberrob?
What was the intention?

**Comment by huberrob** [comment]
I think there was a conflict with connexion or Werkzeug, but not sure..

**Comment by afuetterer** [comment]
Alright, I will investigate. I updated to the last version 2.14 of connexion in #407. Which works fine.
If it works with flask-limiter 3.5 I will drop this constraint.

connexion team is also working on a version 3.0.0.

**Comment by afuetterer** [comment]
All done.
