### ISSUE TITLE
Add coveralls integration

### ISSUE THREAD

**Issue by afuetterer** [pangaea-data-publisher/fuji#515]
## Tasks

- [x] add coverage badge to readme
- [x] remove obsolete manual upload of coverage and test reports in .github/workflows/ci.yml
- [x] remove custom .github/workflows/reports.yml
- [x] add coverallsapp/github-action to .github/workflows/ci.yml
- [x] remove obsolete cov-badge and cov-ci scripts
- [x] remove obsolete genbadge dependency

## Open PRs

- [x] #512
- [ ] #514
